### ISSUE TITLE
Output file (or fix output variable)

### ISSUE THREAD

**Issue by lgmorand** [stackrox/kube-linter-action#3]
I'd love to extract results as a txt file and use it afterwards, either as artifact of the workflow run or au create a bug with the content of the results.

Could you add an optional parameter to specify the output file ?

**Comment by lgmorand** [comment]
I created a fully working implementation and while reviewing code, I discovered the output variable

the variable is undocumented but furthermore I'm not sure that it works. I don't see where the value of lint-txt is set. When I'm trying to reuse it, value is empty

Am I crazy ?

**Comment by neilcar** [comment]
@lgmorand You're not crazy but I might be.

I've released a new version that adds an output file to the workspace.  You can capture that as an artifact like this:

```
      - name: Scan repo
        id: kube-lint-repo
        uses: ./.github/actions/kube-lint
        with:
          directory: yamls
          config: .kube-linter/config.yaml
      - name: Archive kube-linter output
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: kube-linter-output
          path: kubelinter.log
```

There's also a new input parameter for the name of the output file (in case you're running the action multiple times against different files, for example).

I've removed the unimplemented output variable.  GH actions `set-output` doesn't support capturing multi-line output so we'd have to do substitution on the output to make it work; then, after that's done, the kubelinter output has both single & double quotes in it which made it nearly impossible to consume the output variable in another step.  (There may be a better pattern to make this work but I couldn't figure it out.)
